---
S823_call2arrivaltitle: "S823_call2arrival"
author: "fk506cni"
date: "2025-04-03"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
require(tidyverse)
require(openxlsx)
require(DT)
require(tictoc)
require(data.table)
require(officer)
require(lubridate)
require(ggpubr)
require(gt)
require(extrafont)
require(arrow)
require(svglite)
loadfonts(quiet = T)
```


```{r}
outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  f2metajson(file_name)
  
  # #pdf
  # file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  # ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  # f2metajson(file_name)
  #svg
  file_name <- paste(outputdir,plot_name, ".svg", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "svg",width = wid, height = hei,dpi = 300,units = "cm")
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
  # f2metajson(file_name)
  
  grid::grid.draw(plot)
  
}



inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}


f2metajson <- function(f){
  l <- file.info(f) %>% as.list()
  l2 <- list()
  
  l2 <- list()
  l_names <- names(l)
  
  for (i in 1:length(l)){
    if(l_names[i] %in% c("uid", "gid", "mode", "uname", "grname")){
      # print(l_names[i])
    }else{
      if("POSIXct" %in% class(l[[i]])){
        l2[[l_names[i]]] <- l[[i]] %>% 
          lubridate::ymd_hms() %>% 
          as.character()
      }else{
        l2[[l_names[i]]] <- as.character(l[[i]])
      }
    }
  }
  
  l2$f <- f
  l2$md5 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::md5() %>% 
    as.character() %>% 
    as.character()
  l2$sha256 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::sha256() %>% 
    as.character() %>% 
    as.character()
  print(l2)
  f_json <- paste(f, ".json", sep="", collapse = "")
  jsonlite::write_json(x = l2, path = f_json, pretty=T, auto_unbox=T)
  # return(l2)
  # # jsonlite::write_json(x = l2, path = f_json)
}


get_ts <- function(){
  ts <- Sys.time() %>% 
    as.character() %>% 
    str_replace_all(" ", "_") %>% 
    str_replace_all("\\-|:", "")
  return(ts)
}


```


```{r}
ts <- get_ts()
ts
```

```{r}
f_d <- "../../../../anal/Prj58_mpac/map/P528_map_pptx_parse/note/pos.parquet"
dst <- read_parquet(f_d)

dst %>% DT::datatable()
```


```{r}
fs <- list.files("../../map/", pattern = "out*", full.names = T)
fs

l <- list()
for(f in fs){
  print(f)
  d <- openxlsx::read.xlsx(f) %>% 
    mutate(f = f)
  l[[f]] <- d
  
}

ar <- rbindlist(l, fill = T) %>% 
  mutate(case = f %>% 
           as.factor() %>% 
           as.numeric() %>% 
           magrittr::add(5) %>% 
           str_c("Case:", ., sep="") %>% 
           factor(., levels = unique(.))) %>% 
  filter(!is.na(time_call_to_toch)) %>% 
  mutate(m =  time_call_to_toch %>% 
           str_extract(., "^[0-9]*min") %>% 
           str_remove("min") %>% 
           as.numeric(),
         s =  time_call_to_toch %>% 
           str_extract(., "[0-9]*sec") %>% 
           str_remove("sec") %>% 
           as.numeric()) %>% 
  mutate(t2a = 60*m + s) %>%
  rename(pos = label) %>% 
  left_join(dst, by = "pos")


```

Time to arrival (sec) = 0.81 * Distance from CT Reading Room (m) +  47.3

```{r}
m <- glm(formula = t2a ~ d, 
         data = ar)
msr <- m %>% summary()
int_slp <- msr %>% coef() %>% as.data.frame() %>% .[["Estimate"]]
print(int_slp)

t <- "y = 0.81 * x +  47.3"

p_t2a <- ggplot()+
  theme_pubr(base_family = "Times New Roman",
             legend = c(0.15, 0.85))+
  theme(aspect.ratio = 1)+
  geom_abline(slope = int_slp[2],
              intercept = int_slp[1]) +
  geom_point(
    data = ar,
    aes(x=d,
        y=t2a,
        color=case)
  )+
  annotate("text", x=150,   y=250, label=t,
           family= "Times New Roman")+
  xlab("Distance from CT Reading Room (m): x")+
  ylab("Time to arrival (sec): y")+coord_cartesian()
p_t2a


ggsave2_tri(p_t2a, wid=12, hei=12)
```


```{r}
sessionInfo()
```

